import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { ClerkProvider, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import { SignInButton } from '@/components/SignInButton'
import './globals.css'

const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
})
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider>
			<html lang='en' suppressHydrationWarning>
				<body
					className={`${geistSans.variable} ${geistMono.variable} font-sans bg-background text-foreground`}
				>
					<header className='p-4 flex justify-end'>
						<SignedOut>
							<SignInButton />
						</SignedOut>
						<SignedIn>
							<UserButton afterSignOutUrl='/' />
						</SignedIn>
					</header>
					<main className='container mx-auto px-4'>{children}</main>
				</body>
			</html>
		</ClerkProvider>
	)
}
